// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr3ixodZhgovqPl9tDRSvxBAklysayanc',
    appId: '1:648901114811:web:5717e2af04e4baf35ba29e',
    messagingSenderId: '648901114811',
    projectId: 'doctors-point-99107',
    authDomain: 'doctors-point-99107.firebaseapp.com',
    storageBucket: 'doctors-point-99107.appspot.com',
    measurementId: 'G-YVX830WKHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA79eOS-Ykcb4VP5kMX5-mRPJHqj3EAo8w',
    appId: '1:648901114811:android:94cfe707c8f12e585ba29e',
    messagingSenderId: '648901114811',
    projectId: 'doctors-point-99107',
    storageBucket: 'doctors-point-99107.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOVTGizfjCBGNHmHleIf4Z4UFTMhfxKY0',
    appId: '1:648901114811:ios:ee698071aa234dd85ba29e',
    messagingSenderId: '648901114811',
    projectId: 'doctors-point-99107',
    storageBucket: 'doctors-point-99107.appspot.com',
    iosBundleId: 'com.tshadow.doctorsPoint',
  );
}
